name: Docker Image for restaurent app FE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "aditya2khot" --password-stdin
        docker build -t aditya2khot/restaurant-order-frontend:v1 .
        docker push aditya2khot/restaurant-order-frontend:v1
